#!/bin/bash

exec 1> "/tmp/init-container-$HOSTNAME.log" 2>&1

export HOST_DIR="/docker"
export LOG_DIR="$HOST_DIR/logs"
export LOG_FILE="$LOG_DIR/$HOSTNAME.log"

INIT_HOST_SCRIPT="$HOST_DIR/init-host"
if [[ -x "$INIT_HOST_SCRIPT" ]]; then
    echo "running $INIT_HOST_SCRIPT"
    $INIT_HOST_SCRIPT
fi

USER=$1
/create-user $@

su $USER -c "mkdir -p \"$LOG_DIR\""
echo "switching log file to $LOG_FILE"
exec 1> "$LOG_FILE" 2>&1

INIT_APPLICATION_SCRIPT="$HOST_DIR/init-application"

if [[ -x "$INIT_APPLICATION_SCRIPT" ]]; then
    echo "running $INIT_APPLICATION_SCRIPT"
    su $USER -c "$INIT_APPLICATION_SCRIPT"
fi

echo "starting ssh daemon in foreground"
/usr/sbin/sshd -D
